#!bin/sh

# For trigger efficiencies
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016B 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016C 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016D 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016E 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016F 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016G 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016H 20

# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu 40
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W1JetsToLNu 40
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W2JetsToLNu 40
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W3JetsToLNu 40
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W4JetsToLNu 40

# For the rest of measurement
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016B 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016C 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016D 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016E 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016F 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016G 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf SingleMuon_Run2016H 20

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016B 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016C 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016D 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016E 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016F 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016G 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf JetHT_Run2016H 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016B 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016C 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016D 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016E 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016F 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016G 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_Data_2016.conf MET_Run2016H 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W1JetsToLNu 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W2JetsToLNu 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W3JetsToLNu 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf W4JetsToLNu 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-70To100 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-100To200 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-200To400 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-400To600 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-600To800 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-800To1200 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-1200To2500 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WJetsToLNu_HT-2500ToInf 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-100To200 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-200To400 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-400To600 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-600To800 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-800To1200 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-1200To2500 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZJetsToNuNu_HT-2500ToInf 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf DYJetsToLL_M-50 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf DY1JetsToLL_M-50 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf DY2JetsToLL_M-50 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf DY3JetsToLL_M-50 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf DY4JetsToLL_M-50 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf TT 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ST_t-channel_top_4f_inclusiveDecays 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ST_t-channel_antitop_4f_inclusiveDecays 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ST_tW_antitop_5f_inclusiveDecays 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ST_tW_top_5f_inclusiveDecays 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WW 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WZ 40
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf ZZ 40

./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WToMuNu_M-200 20
./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016.conf WToTauNu_M-200 20

# For uncertainties
# cp WToMuNu_M-200 WToMuNu_M-200_jesUp
# cp WToMuNu_M-200 WToMuNu_M-200_jesDown
# cp WToMuNu_M-200 WToMuNu_M-200_uesUp
# cp WToMuNu_M-200 WToMuNu_M-200_uesDown
# cp WToMuNu_M-200 WToMuNu_M-200_muUp
# cp WToMuNu_M-200 WToMuNu_M-200_muDown
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_jesUp_WStarMuNu.conf WToMuNu_M-200_jesUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_jesDown_WStarMuNu.conf WToMuNu_M-200_jesDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_uesUp_WStarMuNu.conf WToMuNu_M-200_uesUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_uesDown_WStarMuNu.conf WToMuNu_M-200_uesDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_muUp_WStarMuNu.conf WToMuNu_M-200_muUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_muDown_WStarMuNu.conf WToMuNu_M-200_muDown 20

# cp WToTauNu_M-200 WToTauNu_M-200_jesUp
# cp WToTauNu_M-200 WToTauNu_M-200_jesDown
# cp WToTauNu_M-200 WToTauNu_M-200_uesUp
# cp WToTauNu_M-200 WToTauNu_M-200_uesDown
# cp WToTauNu_M-200 WToTauNu_M-200_taues_1prong0pizerosUp
# cp WToTauNu_M-200 WToTauNu_M-200_taues_1prong0pizerosDown
# cp WToTauNu_M-200 WToTauNu_M-200_taues_1prongUpTo4pizerosUp
# cp WToTauNu_M-200 WToTauNu_M-200_taues_1prongUpTo4pizerosDown
# cp WToTauNu_M-200 WToTauNu_M-200_taues_3prong0pizerosUp
# cp WToTauNu_M-200 WToTauNu_M-200_taues_3prong0pizerosDown
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_1prong0pizerosDown_WStarTauNu.conf WToTauNu_M-200_taues_1prong0pizerosDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_1prong0pizerosUp_WStarTauNu.conf  WToTauNu_M-200_taues_1prong0pizerosUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_1prongUpTo4pizerosDown_WStarTauNu.conf WToTauNu_M-200_taues_1prongUpTo4pizerosDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_1prongUpTo4pizerosUp_WStarTauNu.conf WToTauNu_M-200_taues_1prongUpTo4pizerosUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_3prong0pizerosDown_WStarTauNu.conf WToTauNu_M-200_taues_3prong0pizerosDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_taues_3prong0pizerosUp_WStarTauNu.conf WToTauNu_M-200_taues_3prong0pizerosUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_jesUp_WStarTauNu.conf WToTauNu_M-200_jesUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_jesDown_WStarTauNu.conf WToTauNu_M-200_jesDown 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_uesUp_WStarTauNu.conf WToTauNu_M-200_uesUp 20
# ./HTC_submit_seq.sh NtupleMaker_TauID_all_eras analysisNTupleProducer_tauid_MC_2016_uesDown_WStarTauNu.conf WToTauNu_M-200_uesDown 20
